# 前端页面功能（OS 存储仿真台）：约束 StorageService 暴露的稳定页接口契约，
# 间接支撑仿真台交互，本身不直接渲染到页面。
"""
操作系统子系统对数据库暴露的稳定页接口协议。

功能：
- 约束数据库模块只依赖页服务抽象，而不直接依赖底层文件、缓存或 WAL 实现细节。
- 规定分配页、释放页、读写页、checkpoint 和状态统计等核心能力。

对应需求文档：
- 第 3 节“总体架构（建议）”中的 Storage API。
- 第 6.1 节“必备 API 列表”。
- 第 7.1 节“数据库如何使用本子系统（对接约束）”。
"""

from typing import Protocol


class PageStore(Protocol):
    """数据库模块只依赖稳定页接口，不依赖文件、缓存或 WAL 实现细节。"""
    def allocate_page(self)->int:...
    def free_page(self,page_id:int)->None:...
    def release_page(self,page_id:int)->None:...
    def get_page(self,page_id:int)->bytes:...
    def read_page(self,page_id:int)->bytes:...
    def write_page(self,page_id:int,payload:bytes)->int:...
    def flush_page(self,page_id:int)->None:...
    def flush_all(self)->dict:...
    def get_table_pages(self,table_name:str)->list[int]:...
    def append_table_page(self,table_name:str)->int:...
    def checkpoint(self)->dict:...
    def stats(self)->dict:...
